version: "3"

x-base-app-conf: &base_app_conf # env_file: .env
  stdin_open: true
  tty: true

services:
  django_app:
    <<: *base_app_conf
    image: django_app:latest
    container_name: django_app
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./app:/app"
    environment:
      - OPENAI_API_KEY=sk-ajckfxo0yK_potdZEFZgalO8Gwov1XJ9rJGBArRSYqT3BlbkFJUurgPuc1U161SbQl1PKhgS4FPf9TmsP9-UYzkIFasA
    depends_on:
      - db
      - elasticsearch
      - django-migrations

  # Apply Django migrations
  django-migrations:
    <<: *base_app_conf
    image: django_app:latest
    container_name: django-migrations
    command: python manage.py migrate
    restart: "no"
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - "./app:/app"
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  elasticsearch:
    image: elasticsearch:8.10.3
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  celery_worker:
    <<: *base_app_conf
    image: django_app:latest
    container_name: celery_worker
    restart: always
    command: celery -A sis_exercise worker --pool=solo --loglevel=info
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - "./app:/app"
    depends_on:
      - django_app
      - rabbitmq

  celery_beat:
    <<: *base_app_conf
    image: django_app:latest
    container_name: celery_beat
    restart: always
    command: celery -A sis_exercise beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - "./app:/app"
    depends_on:
      - django_app
      - rabbitmq

volumes:
  elasticsearch_data:
